language: node_js
node_js:
  - 0.8
  - 0.10

before_install:
  # http://blog.npmjs.org/post/78085451721/npms-self-signed-certificate-is-no-more
  - npm config set ca ""

before_script:
  # For Firefox support.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run-script check
  - node_modules/.bin/mocha-phantomjs notes/test/test.html
  - node_modules/.bin/grunt karma:ci
